language: node_js
node_js:
- 4.4.7
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in blog.enc -out blog -d
- node scripts/run.js buildImage
script:
- ls -lah
- node scripts/run.js build
- ls -lah
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/blog
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/deploy.js
  on:
    all_branches: true